### PR TITLE
Error e2e command if no e2e results

### LINKED ISSUE #623: sonobuoy fails to run but report failed tests: 0
**What steps did you take and what happened:**
sonobuoy fails to run 
````
time="2019-03-05T17:25:52Z" level=info msg="Starting annotation update routine"
time="2019-03-05T17:25:52Z" level=info msg="Starting aggregation server" address=0.0.0.0 port=8080
time="2019-03-05T17:25:52Z" level=info msg="Running plugin" plugin=e2e
time="2019-03-05T17:25:52Z" level=info msg="Running plugin" plugin=systemd-logs
time="2019-03-05T17:29:56Z" level=info msg="received aggregator request" client_cert=systemd-logs node=ipv4-worker1 plugin_name=systemd_logs
time="2019-03-05T17:30:17Z" level=info msg="received aggregator request" client_cert=systemd-logs node=ipv4-control-plane plugin_name=systemd_logs
time="2019-03-05T17:30:18Z" level=info msg="received aggregator request" client_cert=systemd-logs node=ipv4-worker2 plugin_name=systemd_logs
time="2019-03-05T18:30:02Z" level=info msg="received aggregator request" client_cert=systemd-logs node=ipv4-worker1 plugin_name=systemd_logs
time="2019-03-05T18:30:02Z" level=warning msg="Got a duplicate result systemd_logs/ipv4-worker1"
time="2019-03-05T18:30:23Z" level=info msg="received aggregator request" client_cert=systemd-logs node=ipv4-control-plane plugin_name=systemd_logs
time="2019-03-05T18:30:23Z" level=warning msg="Got a duplicate result systemd_logs/ipv4-control-plane"
time="2019-03-05T18:30:25Z" level=info msg="received aggregator request" client_cert=systemd-logs node=ipv4-worker2 plugin_name=systemd_logs
time="2019-03-05T18:30:25Z" level=warning msg="Got a duplicate result systemd_logs/ipv4-worker2"
time="2019-03-05T19:30:09Z" level=info msg="received aggregator request" client_cert=systemd-logs node=ipv4-worker1 plugin_name=systemd_logs
time="2019-03-05T19:30:09Z" level=warning msg="Got a duplicate result systemd_logs/ipv4-worker1"
time="2019-03-05T19:30:34Z" level=info msg="received aggregator request" client_cert=systemd-logs node=ipv4-control-plane plugin_name=systemd_logs
time="2019-03-05T19:30:34Z" level=warning msg="Got a duplicate result systemd_logs/ipv4-control-plane"
time="2019-03-05T19:30:36Z" level=info msg="received aggregator request" client_cert=systemd-logs node=ipv4-worker2 plugin_name=systemd_logs
time="2019-03-05T19:30:36Z" level=warning msg="Got a duplicate result systemd_logs/ipv4-worker2"
time="2019-03-05T19:30:40Z" level=info msg="received aggregator request" client_cert=e2e plugin_name=e2e
time="2019-03-05T19:30:40Z" level=info msg="Last update to annotations on exit"
time="2019-03-05T19:30:40Z" level=info msg="Running non-ns query"
time="2019-03-05T19:30:41Z" level=error msg="error querying CustomResourceDefinitions: the server could not find the requested resource"
time="2019-03-05T19:30:41Z" level=info msg="Collecting Node Configuration and Health..."
time="2019-03-05T19:30:41Z" level=info msg="Creating host results for ipv4-control-plane under /tmp/sonobuoy/f3ef6572-6a97-4978-9025-98f7a84b02b2/hosts/ipv4-control-plane\n"
time="2019-03-05T19:30:41Z" level=info msg="Creating host results for ipv4-worker1 under /tmp/sonobuoy/f3ef6572-6a97-4978-9025-98f7a84b02b2/hosts/ipv4-worker1\n"
time="2019-03-05T19:30:41Z" level=info msg="Creating host results for ipv4-worker2 under /tmp/sonobuoy/f3ef6572-6a97-4978-9025-98f7a84b02b2/hosts/ipv4-worker2\n"
time="2019-03-05T19:30:41Z" level=info msg="Running ns query (default)"
time="2019-03-05T19:30:43Z" level=info msg="Running ns query (heptio-sonobuoy)"
time="2019-03-05T19:30:45Z" level=info msg="Collecting Pod Logs..."
time="2019-03-05T19:30:48Z" level=info msg="Running ns query (kube-public)"
time="2019-03-05T19:30:50Z" level=info msg="Running ns query (kube-system)"
time="2019-03-05T19:30:52Z" level=info msg="Results available at /tmp/sonobuoy/201903051725_sonobuoy_f3ef6572-6a97-4978-9025-98f7a84b02b2.tar.gz"
time="2019-03-05T19:30:52Z" level=info msg="no-exit was specified, sonobuoy is now blocking"
````
However it reports that has 0 failed tests
```
# sonobuoy retrieve
201903051725_sonobuoy_f3ef6572-6a97-4978-9025-98f7a84b02b2.tar.gz
# sonobuoy e2e 201903051725_sonobuoy_f3ef6572-6a97-4978-9025-98f7a84b02b2.tar.gz
failed tests: 0
```
but no test ran
```
sonobuoy e2e --show=passed 201903051725_sonobuoy_f3ef6572-6a97-4978-9025-98f7a84b02b2.tar.gz

passed tests: 0
```

**What did you expect to happen:**

sonobuoy should report an error or indicate that didn't run any test at all. Current message is misleading and gives the false impression that everything went right.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Sonobuoy version: v0.13.0
- Kubernetes version: (use `kubectl version`): v1.11.0
- Kubernetes installer & version: kind 0.2.0-alpha & v1.13.4
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): 
- Sonobuoy tarball (which contains * below)

### PR DESCRIPTION
**Pull request by johnSchnake**
Currently, if a user passes a tar which does
not have the e2e results at all, sonobuoy
e2e would report 0 failures which can be
very misleading.

If the file does not exist and is not inspected
then we error saying we couldn't find the file.

Fixes #623

Signed-off-by: John Schnake <jschnake@vmware.com>

**Release note**:
```
"sonobuoy e2e" will now report an error when the archive does not contain e2e results.
```

### CODE REVIEW

File: pkg/client/results/reader_test.go [hunk 1]
```diff
@@ -26,7 +26,7 @@ import (
 	"path/filepath"
 	"testing"
 
-	"k8s.io/api/core/v1"
+	v1 "k8s.io/api/core/v1"
```
Comment (stevesloka) [inline pkg/client/results/reader_test.go]: nit: This alias isn't needed

File: pkg/client/e2e.go [hunk 2]
```diff
@@ -32,14 +34,25 @@ import (
...
+				return err
+			}
+			// TODO(chuckha) consider reusing this function for any generic e2e-esque plugin results.
+			// TODO(chuckha) consider using path.Join()
+			if path == e2eJunitPath {
+				found = true
+			}
+			return results.ExtractFileIntoStruct(e2eJunitPath, path, info, &junitResults)
+		})
+	if !found {
```
Comment (stevesloka) [inline pkg/client/e2e.go]: Should we check the error first to see if the read failed, just so it's clear that the file was found, but it errored in some way.

File: pkg/client/results/reader_test.go (hunk 1 above)
Comment (johnSchnake) [reply pkg/client/results/reader_test.go]: I know; my editor (vscode) seems to really try and force it though. It does it automatically on save. I've been meaning to take a look at why (I figure it is just using goimports; maybe its out of date or something?)

File: pkg/client/e2e.go (hunk 2 above)
Comment (johnSchnake) [reply pkg/client/e2e.go]: If it wasn't found then it wouldn't have failed when reading; it will never try to read the file before setting `found=true`

File: pkg/client/results/reader_test.go (hunk 1 above)
Comment (johnSchnake) [reply pkg/client/results/reader_test.go]: So:
 - I do have the newest version
 - this is actually tested behavior and I think it results from the fact that the path there isnt the actual path of the package. See [this change](https://github.com/golang/tools/commit/864069cfd1b106326ae556b3ca5c1d6b94645987).
 - I _thought_ that was the right path but it is actually a symlink to the staging directory:
```
$ ls -lah ~/go/src/github.com/kubernetes/kubernetes/vendor/k8s.io/
... ...  api -> ../../staging/src/k8s.io/api
```

**Comment by johnSchnake** [comment]
@stevesloka rebased and I think I've addressed your comments appropriately. LGTY?

File: pkg/client/e2e.go (hunk 2 above)
Comment (stevesloka) [reply pkg/client/e2e.go]: I'm thinking broader if some error happens and `err` is returned. We're checking if `!found` first before dealing with the possible error that gets returned. 

Maybe I'm not reading the code correctly on how the flow works.

Comment (johnSchnake) [reply pkg/client/e2e.go]: Yea, its a function thats just being passed to the file-walker.

So the function itself takes an error so that when you look at file-2 you can check if the walker failed when looking at file-1. Here we just stop at the first error ever encountered.

In addition, if you look at the `ExtractFileIntoStruct` it just does nothing unless the path of the current file matches the one you're looking for.

I could make it more clear by by just stating that if the paths arent the same to just return nil. It wouldn't be functionally different than it is now but it wouldn't require you to know how the `ExtractFileIntoStruct` is implemented. 👍

Comment (stevesloka) [reply pkg/client/e2e.go]: Here's the flow I'm seeing:

1. `found == false` (as default)
2. `read.WalkFiles(func())` returns an error
3. Line 53 checks if `found == false` which it is since that's the default. The code then tells the user that it `failed to find results file` when really the file could be there, but extracting or something else returned an error. 
4. err isn't checked until line 58

Comment (johnSchnake) [reply pkg/client/e2e.go]: :dunce:

Thanks for walking me through it! I was looking at the other `err` and thinking that's what you meant. I hadn't even noticed the other one because it was so far away!

For some reason the original writers wanted to define the slice even if they were going to return an empty one. I just return a nil slice and its fine so I rightfully moved it up higher in the code flow.

I updated the tests to confirm the proper code flow in each of them. It makes the tests brittle because of tying the message into the test, but I don't think its a terrible burden to carry for now :)

File: pkg/client/results/reader_test.go (hunk 1 above)
Comment (stevesloka) [reply pkg/client/results/reader_test.go]: Honestly, it's a vscode thing, @davecheney pointed it out to be on some other project PR's. There's nothing in golang that requires this.

Comment (johnSchnake) [reply pkg/client/results/reader_test.go]: It isn't a vscode thing; you're the 2nd person to mention that though so I'd be curious why that rumor got started (maybe it used to be true and just isnt?). I just tested with goimports directly and confirmed that it adds the same prefix.

[I came back to this PR just to find my reference to this because it came up again, then your message here compelled me to manually test it.]
