### PR TITLE
Exit with an error instead of panic

### LINKED ISSUE #257: kube-sonobuoy panics if it cannot connect to the API server
In the case that sonobuoy fails to connect to the API server during startup, the process crashes due to a panic. There is no forward progress that could be made in this case, as we are unable to talk to the API server, but I wonder if the error could be handled more gracefully.

```
$ kubectl logs -n heptio-sonobuoy sonobuoy kube-sonobuoy
time="2018-02-15T19:50:17Z" level=info msg="Scanning plugins in ./plugins.d (pwd: /)"
time="2018-02-15T19:50:17Z" level=info msg="unknown template type" filename=..2982_16_02_04_49_46.880772909
time="2018-02-15T19:50:17Z" level=info msg="unknown template type" filename=..data
time="2018-02-15T19:50:17Z" level=info msg="Scanning plugins in /etc/sonobuoy/plugins.d (pwd: /)"
time="2018-02-15T19:50:17Z" level=info msg="Directory (/etc/sonobuoy/plugins.d) does not exist"
time="2018-02-15T19:50:17Z" level=info msg="Scanning plugins in ~/sonobuoy/plugins.d (pwd: /)"
time="2018-02-15T19:50:17Z" level=info msg="Directory (~/sonobuoy/plugins.d) does not exist"
time="2018-02-15T19:50:17Z" level=info msg="Loading plugin driver Job"
time="2018-02-15T19:50:17Z" level=info msg="Filtering namespaces based on the following regex:.*|heptio-sonobuoy"
panic: Get https://10.96.0.1:443/api/v1/namespaces: dial tcp 10.96.0.1:443: getsockopt: no route to host
goroutine 1 [running]:
github.com/heptio/sonobuoy/pkg/discovery.FilterNamespaces(0x18ce0c0, 0xc420206f70, 0xc42038a120, 0x12, 0x1, 0xc42038a120, 0x12)
	/go/src/github.com/heptio/sonobuoy/pkg/discovery/utils.go:44 +0x480
github.com/heptio/sonobuoy/pkg/discovery.Run(0x18ce0c0, 0xc420206f70, 0xc4201028c0, 0x0)
	/go/src/github.com/heptio/sonobuoy/pkg/discovery/discovery.go:77 +0x5c4
github.com/heptio/sonobuoy/cmd/sonobuoy/app.runMaster(0xc4204c26c0, 0xc4204314a0, 0x0, 0x3)
	/go/src/github.com/heptio/sonobuoy/cmd/sonobuoy/app/master.go:63 +0x7c
github.com/heptio/sonobuoy/vendor/github.com/spf13/cobra.(*Command).execute(0xc4204c26c0, 0xc420431380, 0x3, 0x3, 0xc4204c26c0, 0xc420431380)
	/go/src/github.com/heptio/sonobuoy/vendor/github.com/spf13/cobra/command.go:654 +0x2a2
github.com/heptio/sonobuoy/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x19174c0, 0x1, 0x1917940, 0x1917b80)
	/go/src/github.com/heptio/sonobuoy/vendor/github.com/spf13/cobra/command.go:729 +0x2fe
github.com/heptio/sonobuoy/vendor/github.com/spf13/cobra.(*Command).Execute(0x19174c0, 0xc42034bf70, 0xf3ecd4)
	/go/src/github.com/heptio/sonobuoy/vendor/github.com/spf13/cobra/command.go:688 +0x2b
main.main()
	/go/src/github.com/heptio/sonobuoy/cmd/sonobuoy/main.go:25 +0x2d
```

### PR DESCRIPTION
**Pull request by alexbrand**
Fixes #257 

```
Sonobuoy has to perform a couple of operations before actually starting
a test. Instead of panicking when one of these ops fails, return an
error and exit with a non-zero exit code.

Signed-off-by: Alexander Brand <alexbrand09@gmail.com>
```

Failure output sample:
```
INFO[0000] Scanning plugins in ./plugins.d (pwd: /Users/abrand/go/src/github.com/heptio/sonobuoy)
INFO[0000] unknown template type                         filename=e2e.jsonnet
INFO[0000] unknown template type                         filename=heptio-e2e.jsonnet
INFO[0000] unknown template type                         filename=systemd_logs.jsonnet
INFO[0000] Scanning plugins in /etc/sonobuoy/plugins.d (pwd: /Users/abrand/go/src/github.com/heptio/sonobuoy)
INFO[0000] Directory (/etc/sonobuoy/plugins.d) does not exist
INFO[0000] Scanning plugins in ~/sonobuoy/plugins.d (pwd: /Users/abrand/go/src/github.com/heptio/sonobuoy)
INFO[0000] Directory (~/sonobuoy/plugins.d) does not exist
INFO[0000] Loading plugin driver DaemonSet
INFO[0000] Loading plugin driver Job
INFO[0000] Filtering namespaces based on the following regex:.*|heptio-sonobuoy
ERRO[0030] could not filter namespaces: Get https://192.168.99.100:8443/api/v1/namespaces: dial tcp 192.168.99.100:8443: i/o timeout
exit status 1
```

### CODE REVIEW

File: pkg/discovery/discovery.go [hunk 1]
```diff
@@ -35,17 +35,17 @@ import (
...
 	// 1. Create the directory which will store the results, including the
 	// `meta` directory inside it (which we always need regardless of
 	// config)
 	outpath := path.Join(cfg.ResultsDir, cfg.UUID)
 	metapath := path.Join(outpath, MetaLocation)
-	err := os.MkdirAll(metapath, 0755)
+	err = os.MkdirAll(metapath, 0755)
 	if err != nil {
-		panic(err.Error())
+		return errCount, errors.Wrap(err, "could not create directory to store results")
```
Comment (timothysc) [inline pkg/discovery/discovery.go]: So a while ago we used to pass all the errors back to main, but it became weird and counterproductive, because it was always a list of errors and you lost context from where it occurred in the query stream.  

logging the error in place and returning for graceful exit seems sufficient and keeps the funcion consistent.   Otherwise for consistency, we'd have to plumb back the error[] from the queries.

Comment (alexbrand) [reply pkg/discovery/discovery.go]: Ahh I see. So instead of returning the error, Run should:
* Continue to return a single value:`errCount`
* Log the error, increment the count, and return early for graceful exit

Is my understanding correct? Thanks!

Comment (timothysc) [reply pkg/discovery/discovery.go]: @alexbrand - yup!

File: pkg/discovery/discovery.go [hunk 2]
```diff
@@ -45,7 +45,9 @@ func Run(kubeClient kubernetes.Interface, cfg *config.Config) (errCount uint) {
 	metapath := path.Join(outpath, MetaLocation)
 	err := os.MkdirAll(metapath, 0755)
 	if err != nil {
-		panic(err.Error())
+		errCount++
+		errlog.LogError(errors.Wrap(err, "could not create directory to store results"))
+		return errCount
```
Comment (timothysc) [inline pkg/discovery/discovery.go]: can just be `return errCount++` then lgtm

Comment (alexbrand) [reply pkg/discovery/discovery.go]: That's what I tried initially but it seems go does not support that. TIL: https://play.golang.org/p/FjcRXGMMDfz

Comment (timothysc) [reply pkg/discovery/discovery.go]: grumble golang ... `return errCount+1`

Comment (alexbrand) [reply pkg/discovery/discovery.go]: Ahh! Brain fart on my end. Will update.
