### PR TITLE
Preflight check for a DNS pod

### LINKED ISSUE #273: Add detection and pre-flight checks to run
Prior to running we should detect api-enabled (rbac) and preflight (fail-check) on known bad deployments 

// TODO(timothysc) Need to add checks which include (detection-rbac, preflight-DNS, ...)

### PR DESCRIPTION
**Pull request by liztio**
Closes #273

### CODE REVIEW

File: pkg/client/run.go [hunk 1]
```diff
@@ -23,23 +23,34 @@ import (
...
+		}
+		if err := preflightCheck(client); err != nil {
+			return errors.Wrap(err, "preflight check failed")
+		}
+	}
+
 	manifest, err := c.GenerateManifest(&cfg.GenConfig)
 	if err != nil {
-		return errors.Wrap(err, "couldn't run invalid manifest")
+		return errors.Wrap(err, "")
```
Comment (chuckha) [inline pkg/client/run.go]: return err at this point instead of wrapping i think

File: pkg/client/interfaces.go [hunk 2]
```diff
@@ -51,6 +51,7 @@ type E2EConfig struct {
 // RunConfig are the input options for running Sonobuoy.
 type RunConfig struct {
 	GenConfig
+	SkipPreflight bool
```
Comment (chuckha) [inline pkg/client/interfaces.go]: godoc please!
