### PR TITLE
List available Sonobuoy modes

### LINKED ISSUE #228: list available modes in the `gen` command
```
test salazar:sonobuoy cha$ ./main gen --help
Generates a sonobuoy manifest for submission via kubectl

Usage:
  sonobuoy gen [flags]
  sonobuoy gen [command]

Available Commands:
  plugin      Generates the manifest Sonobuoy uses to run a worker for the given plugin

Flags:
  -h, --help                    help for gen
  -m, --mode Name               What mode to run sonobuoy in
      --path string             TBD: location to output (default "./")
  -p, --paths stringArray       the paths to search for the plugins in. Defaults to . and ./plugins.d/ (default [.,./plugins.d/])
      --sonobuoy-image string   The Docker image (as a registry URL) to use for the Sonobuoy controller (default "gcr.io/heptio-images/sonobuoy:latest")

Global Flags:
      --alsologtostderr                  log to standard error as well as files
  -d, --debug                            Enable debug output (includes stack traces)
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                   If non-empty, write log files in this directory
      --logtostderr                      log to standard error instead of files
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
  -v, --v Level                          log level for V logs
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging

Use "sonobuoy gen [command] --help" for more information about a command.
```

I happened to guess that `gen --mode quick` was what I wanted, but we should list all available modes and what they mean.

### PR DESCRIPTION
**Pull request by liztio**
Signed-off-by: liz <liz@heptio.com>

Closes #228

### CODE REVIEW

File: cmd/sonobuoy/app/gen_plugin.go [hunk 1]
```diff
@@ -36,7 +36,7 @@ func init() {
 		Args:  cobra.ExactArgs(1),
 	}
 
-	GenCommand.PersistentFlags().StringArrayVarP(
+	cmd.PersistentFlags().StringArrayVarP(
```
Comment (chuckha) [inline cmd/sonobuoy/app/gen_plugin.go]: this appears to be a stray change, should it be in this commit? (totally cool if it's a bug fix or whatever)

Comment (liztio) [reply cmd/sonobuoy/app/gen_plugin.go]: yeah it's a bug fix I noticed while I was fixing this. The plugin path gets added to the parent command by accident.
