### PR TITLE
Ensure conformance image version is prefixed with 'v'

### LINKED ISSUE #716: kube-conformance-image-version flag strips `v` leading to errors
**What steps did you take and what happened:**
Run `sonobuoy gen --kube-conformance-image-version=v1.14.2 | grep conform` and see that the image is from the heptio-images registry.

**What did you expect to happen:**
For v1.14.2 we should be using the upstream google containers.

**Anything else you would like to add:**
The behavior of the `--kube-conformance-image-version` flag is incorrect. Originally I was going to show you how overriding the image version via that flag would lead to the upstream conformance image (instead of the Heptio one) but, to my surprise, it failed.

The issue there (I'll make another ticket for this) is that there a few paths to getting the image version:
 - the user specified 'auto' (the default) and we asked the server, resuling in something like `v1.14.2`
 - user explicity tells us the version; we even require them to state it with the `v` prefix. However, the logic to `Set` the value strips that `v` prefix because it goes through a semver library to ensure the value is reasonable.

**Environment:**

- Sonobuoy version: v0.14.2

### PR DESCRIPTION
**Pull request by johnSchnake**
**What this PR does / why we need it**:
When using flags to set the kube-conformance-image-version
the `Set` method ends up stripping the `v` prefix which it
requires the user to provide.

This causes a problem because the rest of the codebase assumes
the version will start with that prefix due to the fact that that
is how images are tagged (for Sonobuoy, Heptio kube-conformance,
and for upstream conformance images).

This change just adds the prefix back after validating the version
and updates the tests to actually check for the version that
gets persisted.

**Which issue(s) this PR fixes**
Fixes #716

**Special notes for your reviewer**:
A simple test:
```
$ ./sonobuoy gen --kube-conformance-image-version=v1.14.0|grep conform
$ ./sonobuoy gen --kube-conformance-image-version=v1.14.1|grep conform
```
Both of those should result in images with the tag prefixed with `v`. In addition, the first should be a heptio image, the latter a google image.

As it stands now, the `v` prefix is missing and both try to use the Heptio registry due to the missing prefix affecting the comparison.

**Release note**:
```
Fixes handling of the --kube-conformance-image-version flag so that the resulting conformance image tag is prefixed with 'v' as expected.
```

### CODE REVIEW

File: pkg/image/imageversion.go [hunk 1]
```diff
@@ -59,7 +59,10 @@ func (c *ConformanceImageVersion) Set(str string) error {
 		if err != nil {
 			return err
 		}
-		*c = ConformanceImageVersion(version.String())
+
+		// It is important to set the string with the `v` prefix in order
+		// to be consistent with server version reporting and image tagging norms.
+		*c = ConformanceImageVersion(fmt.Sprintf("v%v", version.String()))
```
Comment (stevesloka) [inline pkg/image/imageversion.go]: Should `ConformanceImageVersion` return the properly formatted string?

Comment (johnSchnake) [reply pkg/image/imageversion.go]: `ConformanceImageVersion` isn't a function, it is just casting the string to the type.

If you meant that "should the `String() string` method on the `ConformanceImageVersion` type do this formatting, I would argue no.  We have a constrained type so if we want validation like this we have to either use custom `Get()` methods (more overhead than we need for a flag wrapper) or just do the proper validation on `Set`.

To put all this logic in the `String` method would be a bit awkward because we wouldn't be able to handle the error case so we'd just end up having to put the logic in both places. And once we fix it here we don't really have a problem which would make it worth copying the logic to `String` as well.
