### PR TITLE
Properly report error when a plugin fails to run

### LINKED ISSUE #559: Failing to launch a plugin shouldn't exit the aggregator server
**What steps did you take and what happened:**
I tested sonobuoy on both a gke cluster and pks cluster. On PKS the tests never complete even after several hours. 

```
hev@Adams-MacBook-Pro-2 ~ $ sonobuoy status
PLUGIN		STATUS	COUNT
e2e		running	1
systemd_logs	running	3

Sonobuoy is still running. Runs can take up to 60 minutes.
hev@Adams-MacBook-Pro-2 ~ $ kubectl get pods -n heptio-sonobuoy
NAME       READY   STATUS    RESTARTS   AGE
sonobuoy   1/1     Running   0          16h
hev@Adams-MacBook-Pro-2 ~ $
```

**What did you expect to happen:**
On GKE after doing a `sonobuoy run` and waiting an hour so the e2e and systemd_logs tests were completed. 

**Anything else you would like to add:**
This is likely a change required in PKS but I am not sure what that is. Logs fro sonobuoy below.

```
time="2018-11-20T23:14:29Z" level=info msg="Scanning plugins in ./plugins.d (pwd: /)"
time="2018-11-20T23:14:29Z" level=info msg="Scanning plugins in /etc/sonobuoy/plugins.d (pwd: /)"
time="2018-11-20T23:14:29Z" level=info msg="Directory (/etc/sonobuoy/plugins.d) does not exist"
time="2018-11-20T23:14:29Z" level=info msg="Scanning plugins in ~/sonobuoy/plugins.d (pwd: /)"
time="2018-11-20T23:14:29Z" level=info msg="Directory (~/sonobuoy/plugins.d) does not exist"
time="2018-11-20T23:14:29Z" level=info msg="Filtering namespaces based on the following regex:.*|heptio-sonobuoy"
time="2018-11-20T23:14:29Z" level=info msg="Namespace default Matched=true"
time="2018-11-20T23:14:29Z" level=info msg="Namespace heptio-sonobuoy Matched=true"
time="2018-11-20T23:14:29Z" level=info msg="Namespace kube-public Matched=true"
time="2018-11-20T23:14:29Z" level=info msg="Namespace kube-system Matched=true"
time="2018-11-20T23:14:29Z" level=info msg="Namespace pks-system Matched=true"
time="2018-11-20T23:14:29Z" level=info msg="Starting server Expected Results: [{ e2e} {vm-2e6f9853-0e41-423a-6202-73805abaace9 systemd_logs} {vm-a27b4c0f-3d8e-46c2-6779-88e3f409d5b4 systemd_logs} {vm-c7bbf82b-e45b-489b-5d79-d1eecad49e0c systemd_logs}]"
time="2018-11-20T23:14:29Z" level=info msg="Starting annotation update routine"
time="2018-11-20T23:14:29Z" level=info msg="Running plugin" plugin=e2e
time="2018-11-20T23:14:29Z" level=info msg="Starting aggregation server" address=0.0.0.0 port=8080
time="2018-11-20T23:14:29Z" level=info msg="Running plugin" plugin=systemd-logs
time="2018-11-20T23:14:29Z" level=info msg="Last update to annotations on exit"
time="2018-11-20T23:14:29Z" level=error msg="error running plugins: error running plugin systemd-logs: could not create DaemonSet for daemonset plugin systemd-logs: DaemonSet.apps \"sonobuoy-systemd-logs-daemon-set-58f3dfbb6da94645\" is invalid: spec.template.spec.containers[0].securityContext.privileged: Forbidden: disallowed by cluster policy"
time="2018-11-20T23:14:29Z" level=info msg="Running non-ns query"
time="2018-11-20T23:14:29Z" level=error msg="error querying CustomResourceDefinitions: the server could not find the requested resource"
time="2018-11-20T23:14:29Z" level=info msg="Collecting Node Configuration and Health..."
time="2018-11-20T23:14:29Z" level=info msg="Creating host results for vm-2e6f9853-0e41-423a-6202-73805abaace9 under /tmp/sonobuoy/20346e1c-8383-4136-9591-f6acfed2a3df/hosts/vm-2e6f9853-0e41-423a-6202-73805abaace9\n"
time="2018-11-20T23:14:29Z" level=info msg="Creating host results for vm-a27b4c0f-3d8e-46c2-6779-88e3f409d5b4 under /tmp/sonobuoy/20346e1c-8383-4136-9591-f6acfed2a3df/hosts/vm-a27b4c0f-3d8e-46c2-6779-88e3f409d5b4\n"
time="2018-11-20T23:14:30Z" level=info msg="Creating host results for vm-c7bbf82b-e45b-489b-5d79-d1eecad49e0c under /tmp/sonobuoy/20346e1c-8383-4136-9591-f6acfed2a3df/hosts/vm-c7bbf82b-e45b-489b-5d79-d1eecad49e0c\n"
time="2018-11-20T23:14:31Z" level=info msg="Running ns query (default)"
time="2018-11-20T23:14:33Z" level=info msg="Running ns query (heptio-sonobuoy)"
time="2018-11-20T23:14:34Z" level=info msg="Collecting Pod Logs..."
time="2018-11-20T23:14:34Z" level=error msg="the server rejected our request for an unknown reason (get pods sonobuoy-e2e-job-f2f7a7acac314762)"
time="2018-11-20T23:14:35Z" level=info msg="Running ns query (kube-public)"
time="2018-11-20T23:14:37Z" level=info msg="Running ns query (kube-system)"
time="2018-11-20T23:14:40Z" level=info msg="Running ns query (pks-system)"
time="2018-11-20T23:14:42Z" level=info msg="Results available at /tmp/sonobuoy/201811202314_sonobuoy_20346e1c-8383-4136-9591-f6acfed2a3df.tar.gz"
time="2018-11-20T23:14:42Z" level=info msg="no-exit was specified, sonobuoy is now blocking"
```

**Environment:**

- Sonobuoy version: 0.12.1
- Kubernetes version: (use `kubectl version`): 1.12.2
- Kubernetes installer & version: PKS 1.2.2-build.3
- Cloud provider or hardware configuration: GCP
- OS (e.g. from `/etc/os-release`): 
- Sonobuoy tarball (which contains * below)

### PR DESCRIPTION
**Pull request by johnSchnake**
**What this PR does / why we need it**:
Currently the logic of the aggregator short circuits when a
plugin fails to `Run` without error. It exits abruptly and does
not launch other plugins or report the failure on the plugin
status.

This commit changes the following behavior:
 - ensures we can create all the auth certs needed before launching
any plugins, ensuring we don't fail to generate some certs after
other plugins are already running.
 - when a plugin fails to Run without error, we send a failing
result so that the aggregator properly reports the status of
the plugin as an error and the results tarball shows the error
as expected.

**Which issue(s) this PR fixes**
Fixes #559

**Special notes for your reviewer**:
No good test for the entire logic here, I can attach some screenshots of when I modified the code to force an error though.

**Release note**:
```
The aggregator server will now report a plugin as failed if it can't properly be started and will continue starting other plugins.
```

### CODE REVIEW

File: pkg/plugin/aggregation/run.go [hunk 1]
```diff
@@ -150,14 +152,22 @@ func Run(client kubernetes.Interface, plugins []plugin.Interface, cfg plugin.Agg
 	}()
 
 	// 4. Launch each plugin, to dispatch workers which submit the results back
+	certs := map[string]*tls.Certificate{}
```
Comment (johnSchnake) [inline pkg/plugin/aggregation/run.go]: This is a weird diff, but the point was that the loop over plugins did 2 things:
 - create cert
 - run plugin

If we can't create certs I think that is a completely different type of error condition and I'm OK with maintaining the existing behavior where the server does a hard return there. I pulled it into its own loop to more clearly separate the two operations so that we wouldn't have some plugins already started, fail to generate the next cert, then return from that function (without completing the function to ingest results, update status, etc)

File: pkg/plugin/driver/job/job.go [hunk 2]
```diff
@@ -64,7 +64,7 @@ func NewPlugin(dfn plugin.Definition, namespace, sonobuoyImage, imagePullPolicy,
 // a Job only launches one pod, only one result type is expected.
 func (p *Plugin) ExpectedResults(nodes []v1.Node) []plugin.ExpectedResult {
 	return []plugin.ExpectedResult{
-		plugin.ExpectedResult{ResultType: p.GetResultType()},
+		{ResultType: p.GetResultType()},
```
Comment (johnSchnake) [inline pkg/plugin/driver/job/job.go]: TIL that this is a gofmt simplification. I thought you had to put the type there.

File: pkg/plugin/aggregation/run.go [hunk 3]
```diff
@@ -150,14 +152,22 @@ func Run(client kubernetes.Interface, plugins []plugin.Interface, cfg plugin.Agg
...
+
+	for _, p := range plugins {
 		logrus.WithField("plugin", p.GetName()).Info("Running plugin")
-		if err = p.Run(client, cfg.AdvertiseAddress, cert); err != nil {
-			return errors.Wrapf(err, "error running plugin %v", p.GetName())
+		if err = p.Run(client, cfg.AdvertiseAddress, certs[p.GetName()]); err != nil {
+			err = errors.Wrapf(err, "error running plugin %v", p.GetName())
+			logrus.Error(err)
+			monitorCh <- utils.MakeErrorResult(p.GetResultType(), map[string]interface{}{"error": err.Error()}, "")
+			continue
```
Comment (johnSchnake) [inline pkg/plugin/aggregation/run.go]: These 4 lines are the real change:
 - form the error with wrap
 - log it
 - send the error result (taken from the `Monitor` code)
 - continue with next plugin and the rest of aggregator operations.

**Comment by johnSchnake** [comment]
Screen Shot 2019-05-15 at 1 39 43 PM
Screen Shot 2019-05-15 at 1 40 26 PM
Screen Shot 2019-05-15 at 1 41 44 PM
