### PR TITLE
Non-namespaced objects can already exist for `sonobuoy run`.

### LINKED ISSUE #291: Run should not exit if it cannot create an object
When run creates objects from the manifest it should not exit if it fails to create the service account just because the service account already exists.

Reproduce: do a sonobuoy run, delete the heptio-sonobuoy namespace, try to `sonobuoy run --mode=quick --preflight` and you get 

```
ERRO[0002] error attempting to run sonobuoy: failed to create object: failed to create API resource sonobuoy-serviceaccount: clusterrolebindings.rbac.authorization.k8s.io "sonobuoy-serviceaccount" already exists 
```

which isn't really an error state

### PR DESCRIPTION
**Pull request by liztio**
Closes #291 

```
$ sonobuoy run --mode quick -n liz-test
INFO[0000] created object                                name=liz-test namespace= resource=namespaces
INFO[0000] created object                                name=sonobuoy-serviceaccount namespace=liz-test resource=serviceaccounts
INFO[0000] created object                                name=sonobuoy-serviceaccount namespace= resource=clusterrolebindings
INFO[0000] created object                                name=sonobuoy-serviceaccount namespace= resource=clusterroles
INFO[0000] created object                                name=sonobuoy-config-cm namespace=liz-test resource=configmaps
INFO[0000] created object                                name=sonobuoy-plugins-cm namespace=liz-test resource=configmaps
INFO[0000] created object                                name=sonobuoy namespace=liz-test resource=pods
INFO[0000] created object                                name=sonobuoy-master namespace=liz-test resource=services
$ sonobuoy run --mode quick -n liz-test2
INFO[0000] created object                                name=liz-test2 namespace= resource=namespaces
INFO[0000] created object                                name=sonobuoy-serviceaccount namespace=liz-test2 resource=serviceaccounts
INFO[0000] object already exists                         name=sonobuoy-serviceaccount namespace= resource=clusterrolebindings
INFO[0000] object already exists                         name=sonobuoy-serviceaccount namespace= resource=clusterroles
INFO[0000] created object                                name=sonobuoy-config-cm namespace=liz-test2 resource=configmaps
INFO[0000] created object                                name=sonobuoy-plugins-cm namespace=liz-test2 resource=configmaps
INFO[0000] created object                                name=sonobuoy namespace=liz-test2 resource=pods
INFO[0000] created object                                name=sonobuoy-master namespace=liz-test2 resource=services
```

### CODE REVIEW

File: pkg/client/run.go [hunk 1]
```diff
@@ -115,15 +116,24 @@ func createObject(cfg *rest.Config, obj *unstructured.Unstructured, mapper meta.
...
 		"name":      name,
 		"namespace": namespace,
 		"resource":  resource,
-	}).Info("created object")
+	})
+
+	switch {
+	case err == nil:
+		log.Info("created object")
+	// Some resources (like ClusterRoleBinding and ClusterBinding) aren't
```
Comment (chuckha) [inline pkg/client/run.go]: `kubectl` does an update on the resources that already exist, do you think it's worth replicating that behavior?

Comment (liztio) [reply pkg/client/run.go]: I don't. Either it's the same and everything's fine, or it's different and we risk breaking something in the background. I'd rather fail visibly rather than invisibly.

Comment (liztio) [reply pkg/client/run.go]: though I guess it's more likely to be a stale run than a duplicate run...
